api_platform:
    title: 'Test - API'
    description: 'Here is the documentation of the test API.'
    version: '%app_version%'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 50
            maximum_items_per_page: 200
            client_items_per_page: true
            items_per_page_parameter_name: limit
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        App\Exception\UserAlreadyExistException: 409
        App\Exception\UserConsentAlreadyExistException: 409
        ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException: 400
        App\Exception\NotFoundProviderTransactionException: 404
        App\Exception\InvestmentRecommendationException: 409
        App\Exception\EligibilityException: 409
        App\Exception\ItemNotFoundException: 404
