doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                dbname: '%env(string:DATABASE_NAME)%'
                user: '%env(string:DATABASE_USER)%'
                password: '%env(string:DATABASE_PASSWORD)%'
                host: '%env(string:DATABASE_HOST)%'
                port: '%env(int:DATABASE_PORT)%'
                server_version: '14'
                schema_filter: ~(?<!_view)$~

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
